all: MaquinaCliente.class MaquinaServidorIterativo.class ProcesadorMaquina.class

clean :
	echo "Limpiando..."
	rm ./MaquinaCliente.class ./MaquinaServidorIterativo.class ./ProcesadorMaquina.class

MaquinaCliente.class : MaquinaCliente.java
	javac MaquinaCliente.java

MaquinaServidorIterativo.class : MaquinaServidorIterativo.java
	javac MaquinaServidorIterativo.java

ProcesadorMaquina.class : ProcesadorMaquina.java
	javac ProcesadorMaquina.java
